export const data = JSON.parse("{\"key\":\"v-05c25383\",\"path\":\"/front-end/TypeScript.html\",\"title\":\"\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"常用类型 类型别名 定义一个 Type。 ```ts type Person = { name: string age: number } const person: Person = { name: \\\"xiaoming\\\", age: 18 } ``` 接口 定义一个 Interface。 ```ts interface Person { name: ...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://cholez.gitee.io/docs/docs/front-end/TypeScript.html\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"常用类型 类型别名 定义一个 Type。 ```ts type Person = { name: string age: number } const person: Person = { name: \\\"xiaoming\\\", age: 18 } ``` 接口 定义一个 Interface。 ```ts interface Person { name: ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"俞文健\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"俞文健\\\",\\\"url\\\":\\\"https://github.com/choIez\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"常用类型\",\"slug\":\"常用类型\",\"link\":\"#常用类型\",\"children\":[{\"level\":3,\"title\":\"类型别名\",\"slug\":\"类型别名\",\"link\":\"#类型别名\",\"children\":[]},{\"level\":3,\"title\":\"接口\",\"slug\":\"接口\",\"link\":\"#接口\",\"children\":[]},{\"level\":3,\"title\":\"元组类型\",\"slug\":\"元组类型\",\"link\":\"#元组类型\",\"children\":[]},{\"level\":3,\"title\":\"枚举类型\",\"slug\":\"枚举类型\",\"link\":\"#枚举类型\",\"children\":[]},{\"level\":3,\"title\":\"联合类型\",\"slug\":\"联合类型\",\"link\":\"#联合类型\",\"children\":[]},{\"level\":3,\"title\":\"交叉类型\",\"slug\":\"交叉类型\",\"link\":\"#交叉类型\",\"children\":[]}]},{\"level\":2,\"title\":\"Type vs Interface\",\"slug\":\"type-vs-interface\",\"link\":\"#type-vs-interface\",\"children\":[{\"level\":3,\"title\":\"合并或继承\",\"slug\":\"合并或继承\",\"link\":\"#合并或继承\",\"children\":[]},{\"level\":3,\"title\":\"可扩展性\",\"slug\":\"可扩展性\",\"link\":\"#可扩展性\",\"children\":[]}]},{\"level\":2,\"title\":\"泛型\",\"slug\":\"泛型\",\"link\":\"#泛型\",\"children\":[{\"level\":3,\"title\":\"函数泛型\",\"slug\":\"函数泛型\",\"link\":\"#函数泛型\",\"children\":[]},{\"level\":3,\"title\":\"接口泛型\",\"slug\":\"接口泛型\",\"link\":\"#接口泛型\",\"children\":[]},{\"level\":3,\"title\":\"泛型约束\",\"slug\":\"泛型约束\",\"link\":\"#泛型约束\",\"children\":[]}]},{\"level\":2,\"title\":\"工具类型\",\"slug\":\"工具类型\",\"link\":\"#工具类型\",\"children\":[{\"level\":3,\"title\":\"Record\",\"slug\":\"record\",\"link\":\"#record\",\"children\":[]},{\"level\":3,\"title\":\"Omit\",\"slug\":\"omit\",\"link\":\"#omit\",\"children\":[]}]}],\"readingTime\":{\"minutes\":2.52,\"words\":756},\"filePathRelative\":\"front-end/TypeScript.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
