export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":"主页","i":"home"},["/README.md"]],
  ["v-9f193b48","/after-end/Java-%E7%AE%97%E6%B3%95.html",{"y":"a","t":"Java 算法","i":"java"},["/after-end/Java-算法.html","/after-end/Java-算法.md",":md"]],
  ["v-4bdc49d9","/after-end/Java.html",{"y":"a","t":"Java","i":"java"},[":md"]],
  ["v-4b37b5b6","/after-end/JavaWeb.html",{"y":"a","t":"JavaWeb","i":"java"},[":md"]],
  ["v-d5366e80","/after-end/JDBC.html",{"y":"a","t":"JDBC","i":"java"},[":md"]],
  ["v-be7ce816","/after-end/MySQL.html",{"y":"a","t":"MySQL","i":"mysql"},[":md"]],
  ["v-4da4f6df","/after-end/Python.html",{"y":"a","t":"Python","i":"python"},[":md"]],
  ["v-293e47be","/after-end/",{"y":"a","t":"后端","i":"markdown"},["/after-end/README.md"]],
  ["v-532743b0","/front-end/Ajax.html",{"y":"a","t":"Ajax","i":"ajax"},[":md"]],
  ["v-2571991c","/front-end/Bootstrap.html",{"y":"a","t":"Bootstrap","i":"css"},[":md"]],
  ["v-1b29e767","/front-end/CSS.html",{"y":"a","t":"CSS","i":"css"},[":md"]],
  ["v-f3caeba0","/front-end/ECharts.html",{"y":"a","t":"ECharts","i":"javascript"},[":md"]],
  ["v-64d0b4ca","/front-end/Exceljs.html",{"y":"a","t":"Exceljs","i":"javascript"},[":md"]],
  ["v-7ec79ef8","/front-end/Git.html",{"y":"a","t":"Git","i":"git"},[":md"]],
  ["v-8a5cf900","/front-end/HTML5.html",{"y":"a","t":"HTML5","i":"html"},[":md"]],
  ["v-20d6295a","/front-end/JavaScript-%E7%AE%97%E6%B3%95.html",{"y":"a","t":"JavaScript 算法","i":"javascript"},["/front-end/JavaScript-算法.html","/front-end/JavaScript-算法.md",":md"]],
  ["v-629e50ca","/front-end/JavaScript.html",{"y":"a","t":"JavaScript","i":"javascript"},[":md"]],
  ["v-44c19b62","/front-end/Less.html",{"y":"a","t":"Less","i":"css"},[":md"]],
  ["v-38db00f4","/front-end/Node.html",{"y":"a","t":"Node","i":"nodeJS"},[":md"]],
  ["v-6803712b","/front-end/React.html",{"y":"a","t":"React","i":"react"},[":md"]],
  ["v-8c02d0de","/front-end/",{"y":"a","t":"前端","i":"markdown"},["/front-end/README.md"]],
  ["v-0313a003","/front-end/Threejs.html",{"y":"a","t":"Threejs","i":"javascript"},[":md"]],
  ["v-05c25383","/front-end/TypeScript.html",{"y":"a","t":"TypeScript","i":"typescript"},[":md"]],
  ["v-13a95478","/front-end/Vue.html",{"y":"a","t":"Vue","i":"vue"},[":md"]],
  ["v-f039009e","/front-end/WebGL.html",{"y":"a","t":"WebGL","i":"javascript"},[":md"]],
  ["v-565d13bd","/front-end/Webpack.html",{"y":"a","t":"Webpack","i":"javascript"},[":md"]],
  ["v-5136f8ac","/front-end/Wxapp.html",{"y":"a","t":"Wxapp","i":"wechat"},[":md"]],
  ["v-14f73021","/more/",{"y":"a","t":"其他","i":"markdown"},["/more/README.md"]],
  ["v-2b3ae6f6","/more/%E7%BB%8F%E9%AA%8C%E5%88%86%E4%BA%AB.html",{"y":"a","t":"经验分享","i":"storage"},["/more/经验分享.html","/more/经验分享.md",":md"]],
  ["v-06156be7","/more/%E8%A7%A3%E5%86%B3%E6%8A%A5%E9%94%99.html",{"y":"a","t":"解决报错","i":"debug"},["/more/解决报错.html","/more/解决报错.md",":md"]],
  ["v-60f2d6d4","/more/%E9%9D%A2%E8%AF%95%E5%AE%9D%E5%85%B8.html",{"y":"a","t":"面试宝典","i":"preview"},["/more/面试宝典.html","/more/面试宝典.md",":md"]],
  ["v-5c0dd206","/overview/",{"y":"a","t":"概览","i":"guide"},["/overview/README.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
]
