export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":"Home","i":"home"},["/README.md"]],
  ["v-4e65ec78","/demo/disable.html",{"y":"a","t":"布局与功能禁用","i":"enable","O":3},[":md"]],
  ["v-c151bf32","/demo/encrypt.html",{"y":"a","t":"密码加密的文章","i":"lock"},[":md"]],
  ["v-438ffe52","/demo/markdown.html",{"y":"a","t":"Markdown 展示","i":"markdown","O":2},[":md"]],
  ["v-6e19edb7","/demo/page.html",{"y":"a","t":"页面配置","i":"file","O":1},[":md"]],
  ["v-1473bf53","/demo/",{"y":"a","t":"其他功能","i":"code"},["/demo/README.md"]],
  ["v-075f0a00","/docs/Bug.html",{"y":"a","t":"Bug","i":"debug"},[":md"]],
  ["v-28169398","/docs/Experience.html",{"y":"a","t":"经验分享","i":"storage"},[":md"]],
  ["v-147825fb","/docs/",{"y":"a","t":"概览","i":"home"},["/docs/README.md"]],
  ["v-501d2b0e","/docs/%E9%9D%A2%E8%AF%95.html",{"y":"a","t":"面试","i":"preview"},["/docs/面试.html","/docs/面试.md",":md"]],
  ["v-ea520900","/docs/%E5%89%8D%E7%AB%AF/Ajax.html",{"y":"a","t":"Ajax","i":"ajax"},["/docs/前端/Ajax.html","/docs/前端/Ajax.md",":md"]],
  ["v-224b92c4","/docs/%E5%89%8D%E7%AB%AF/Bootstrap.html",{"y":"a","t":"Bootstrap","i":"css"},["/docs/前端/Bootstrap.html","/docs/前端/Bootstrap.md",":md"]],
  ["v-5aca3f0f","/docs/%E5%89%8D%E7%AB%AF/CSS.html",{"y":"a","t":"CSS","i":"css"},["/docs/前端/CSS.html","/docs/前端/CSS.md",":md"]],
  ["v-6e126450","/docs/%E5%89%8D%E7%AB%AF/ECharts.html",{"y":"a","t":"ECharts","i":"javascript"},["/docs/前端/ECharts.html","/docs/前端/ECharts.md",":md"]],
  ["v-b0a60f1c","/docs/%E5%89%8D%E7%AB%AF/Exceljs.html",{"y":"a","t":"Exceljs","i":"javascript"},["/docs/前端/Exceljs.html","/docs/前端/Exceljs.md",":md"]],
  ["v-833012c0","/docs/%E5%89%8D%E7%AB%AF/Git.html",{"y":"a","t":"Git","i":"git"},["/docs/前端/Git.html","/docs/前端/Git.md",":md"]],
  ["v-d88addb0","/docs/%E5%89%8D%E7%AB%AF/HTML5.html",{"y":"a","t":"HTML5","i":"html"},["/docs/前端/HTML5.html","/docs/前端/HTML5.md",":md"]],
  ["v-425abf02","/docs/%E5%89%8D%E7%AB%AF/JavaScript-%E7%AE%97%E6%B3%95.html",{"y":"a","t":"JavaScript 算法","i":"javascript"},["/docs/前端/JavaScript-算法.html","/docs/前端/JavaScript-算法.md",":md"]],
  ["v-6d1612f3","/docs/%E5%89%8D%E7%AB%AF/JavaScript.html",{"y":"a","t":"JavaScript","i":"javascript"},["/docs/前端/JavaScript.html","/docs/前端/JavaScript.md",":md"]],
  ["v-dbec60b2","/docs/%E5%89%8D%E7%AB%AF/Less.html",{"y":"a","t":"Less","i":"css"},["/docs/前端/Less.html","/docs/前端/Less.md",":md"]],
  ["v-d005c644","/docs/%E5%89%8D%E7%AB%AF/Node.html",{"y":"a","t":"Node","i":"nodeJS"},["/docs/前端/Node.html","/docs/前端/Node.md",":md"]],
  ["v-40ec7ed3","/docs/%E5%89%8D%E7%AB%AF/React.html",{"y":"a","t":"React","i":"react"},["/docs/前端/React.html","/docs/前端/React.md",":md"]],
  ["v-80b5d18e","/docs/%E5%89%8D%E7%AB%AF/",{"y":"a","t":"目录","i":"context"},["/docs/前端/","/docs/前端/README.md","/docs/%E5%89%8D%E7%AB%AF/README.md"]],
  ["v-45efe3ab","/docs/%E5%89%8D%E7%AB%AF/Threejs.html",{"y":"a","t":"Threejs","i":"javascript"},["/docs/前端/Threejs.html","/docs/前端/Threejs.md",":md"]],
  ["v-b7b0e24a","/docs/%E5%89%8D%E7%AB%AF/TypeScript.html",{"y":"a","t":"TypeScript","i":"typescript"},["/docs/前端/TypeScript.html","/docs/前端/TypeScript.md",":md"]],
  ["v-35cbad6c","/docs/%E5%89%8D%E7%AB%AF/Vue.html",{"y":"a","t":"Vue","i":"vue"},["/docs/前端/Vue.html","/docs/前端/Vue.md",":md"]],
  ["v-60cc8d59","/docs/%E5%89%8D%E7%AB%AF/WebGL.html",{"y":"a","t":"WebGL","i":"javascript"},["/docs/前端/WebGL.html","/docs/前端/WebGL.md",":md"]],
  ["v-cd8d5136","/docs/%E5%89%8D%E7%AB%AF/Webpack.html",{"y":"a","t":"Webpack","i":"javascript"},["/docs/前端/Webpack.html","/docs/前端/Webpack.md",":md"]],
  ["v-9f64dd5c","/docs/%E5%89%8D%E7%AB%AF/Wxapp.html",{"y":"a","t":"Wxapp","i":"wechat"},["/docs/前端/Wxapp.html","/docs/前端/Wxapp.md",":md"]],
  ["v-30b40342","/docs/%E5%90%8E%E7%AB%AF/Java-%E7%AE%97%E6%B3%95.html",{"y":"a","t":"Java 算法","i":"java"},["/docs/后端/Java-算法.html","/docs/后端/Java-算法.md",":md"]],
  ["v-dc46929a","/docs/%E5%90%8E%E7%AB%AF/Java.html",{"y":"a","t":"Java","i":"java"},["/docs/后端/Java.html","/docs/后端/Java.md",":md"]],
  ["v-05df520b","/docs/%E5%90%8E%E7%AB%AF/JavaWeb.html",{"y":"a","t":"JavaWeb","i":"java"},["/docs/后端/JavaWeb.html","/docs/后端/JavaWeb.md",":md"]],
  ["v-493594cc","/docs/%E5%90%8E%E7%AB%AF/JDBC.html",{"y":"a","t":"JDBC","i":"java"},["/docs/后端/JDBC.html","/docs/后端/JDBC.md",":md"]],
  ["v-1aceba5b","/docs/%E5%90%8E%E7%AB%AF/MySQL.html",{"y":"a","t":"MySQL","i":"mysql"},["/docs/后端/MySQL.html","/docs/后端/MySQL.md",":md"]],
  ["v-153d9539","/docs/%E5%90%8E%E7%AB%AF/Python.html",{"y":"a","t":"Python","i":"python"},["/docs/后端/Python.html","/docs/后端/Python.md",":md"]],
  ["v-84cdc4b8","/docs/%E5%90%8E%E7%AB%AF/",{"y":"a","t":"目录","i":"context"},["/docs/后端/","/docs/后端/README.md","/docs/%E5%90%8E%E7%AB%AF/README.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
]
